### ISSUE TITLE
back_prototype.sch old schematic component libraries

### ISSUE THREAD

**Issue by dwaq** [ZeroPhone/ZeroPhone-PCBs#15]
When I try to open [back_prototype.sch](https://github.com/ZeroPhone/ZeroPhone-PCBs/blob/master/back_pcb/back_prototype.sch), I see this helper menu. I'm not sure which part is correct, so it's probably best if you correct this issue.

![image](https://cloud.githubusercontent.com/assets/1299430/26156614/e59e4c4a-3ae4-11e7-9775-231d5d3aa3d4.png)

**Comment by CRImier** [comment]
Hi! I updated my KiCad to 4.0.6, and then pressed OK, and it seems to have saved the symbols instead of replacing them. Same was when I opened the front board. You can just press OK on these windows, and the issue will be solved on the next board file update, whoever of us does it first =)

**Comment by CRImier** [comment]
Changes committed and pushed to the repo, thank you!
